platform :ios, '16.0'
use_frameworks!

source 'https://cdn.cocoapods.org/'

target 'DialerID' do
  pod 'FirebaseCore', '~> 11.0'
  pod 'FirebaseAuth', '~> 11.0'
  pod 'FirebaseDatabase', '~> 11.0'
  pod 'GoogleSignIn', '~> 8.0'
  unless ENV['SKIP_LINPHONE'] == '1'
    pod 'linphone-sdk', :path => 'Vendor/linphone-sdk-pod'
  end
end

target 'DialerIDTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
