platform :ios, '16.0'
use_frameworks!

source 'https://cdn.cocoapods.org/'
source 'https://gitlab.linphone.org/BC/public/podspec.git'

target 'DialerID' do
  pod 'FirebaseCore', '~> 11.0'
  pod 'FirebaseAuth', '~> 11.0'
  pod 'FirebaseDatabase', '~> 11.0'
  pod 'GoogleSignIn', '~> 8.0'
  # Appetize / CI cannot use CallKit SIP. Skip the large Linphone download there.
  unless ENV['SKIP_LINPHONE'] == '1'
    pod 'linphone-sdk', '5.3.77'
  end
end

target 'DialerIDTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
